version: "3"
services:
  db:
    image: mongo
    volumes:
      - ./mongo:/data/db
    networks:
      - webnet
    ports:
      - "3030:5432"
  web:
    # replace username/repo:tag with your name and image details
    image: shop-cart
    networks:
      - webnet
    environment:
      DB_HOST: db
    volumes:
      - ./public/src/images:/app/public/src/images
      - ./public/src/uploads:/app/public/src/uploads
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "./dist/server.js"]
    # command: ["node", "./dist/server.js"]
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./public/src/images:/public/src/images
      - ./public/src/uploads:/public/src/uploads
    ports:
      - "8081:80"
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
networks:
  webnet:
