version: "3"
services:
  db:
    image: mongo
    networks:
      - webnet
  web:
    # replace username/repo:tag with your name and image details
    image: shop-cart
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      DB_HOST: db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "./dist/server.js"]
networks:
  webnet:
